# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StoreSystemInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.LoginStackedWidget.setGeometry(QtCore.QRect(0, 0, 1131, 601))
        self.LoginStackedWidget.setObjectName("LoginStackedWidget")
        self.LoginPage = QtWidgets.QWidget()
        self.LoginPage.setObjectName("LoginPage")
        self.LoginStackedWidget.addWidget(self.LoginPage)
        self.MainWidget = QtWidgets.QWidget()
        self.MainWidget.setObjectName("MainWidget")
        self.MainStackedWidget = QtWidgets.QStackedWidget(self.MainWidget)
        self.MainStackedWidget.setGeometry(QtCore.QRect(0, 80, 1131, 521))
        self.MainStackedWidget.setObjectName("MainStackedWidget")
        self.DashBoardPage = QtWidgets.QWidget()
        self.DashBoardPage.setObjectName("DashBoardPage")
        self.frame_4 = QtWidgets.QFrame(self.DashBoardPage)
        self.frame_4.setGeometry(QtCore.QRect(870, 80, 161, 91))
        self.frame_4.setStyleSheet("background-color: #F0F0F0")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 16, 21))
        self.label_6.setObjectName("label_6")
        self.TotalEarnings = QtWidgets.QLabel(self.frame_4)
        self.TotalEarnings.setGeometry(QtCore.QRect(50, 50, 47, 14))
        self.TotalEarnings.setObjectName("TotalEarnings")
        self.MainStackedWidget.addWidget(self.DashBoardPage)
        self.RentalsPage = QtWidgets.QWidget()
        self.RentalsPage.setObjectName("RentalsPage")
        self.RentalsTable = QtWidgets.QTableWidget(self.RentalsPage)
        self.RentalsTable.setGeometry(QtCore.QRect(0, 40, 841, 481))
        self.RentalsTable.setStyleSheet("QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #CCCCCC; \n"
"    border-radius: 10px; \n"
"    \n"
"    padding: 10px; \n"
"    margin: 20px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border-bottom: 1px solid #CCCCCC;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #C3DAF9; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A1A1A; \n"
"    color: #FFFFFF;\n"
"    border: 1px solid #CCCCCC;\n"
"    padding: 5px;\n"
"}")
        self.RentalsTable.setObjectName("RentalsTable")
        self.RentalsTable.setColumnCount(4)
        self.RentalsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.RentalsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RentalsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RentalsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RentalsTable.setHorizontalHeaderItem(3, item)
        self.AddTenantFrame_2 = QtWidgets.QFrame(self.RentalsPage)
        self.AddTenantFrame_2.setGeometry(QtCore.QRect(830, 60, 291, 441))
        self.AddTenantFrame_2.setStyleSheet("background-color: #1A1A1A;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"")
        self.AddTenantFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AddTenantFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AddTenantFrame_2.setObjectName("AddTenantFrame_2")
        self.label_19 = QtWidgets.QLabel(self.AddTenantFrame_2)
        self.label_19.setGeometry(QtCore.QRect(100, 40, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: #FFFFFF;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.AddTenantFrame_2)
        self.label_20.setGeometry(QtCore.QRect(20, 80, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: #FFFFFF;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.AddTenantFrame_2)
        self.label_21.setGeometry(QtCore.QRect(20, 140, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: #FFFFFF;")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.AddTenantFrame_2)
        self.label_22.setGeometry(QtCore.QRect(20, 200, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: #FFFFFF;")
        self.label_22.setObjectName("label_22")
        self.StartDate = QtWidgets.QLineEdit(self.AddTenantFrame_2)
        self.StartDate.setGeometry(QtCore.QRect(30, 220, 241, 20))
        self.StartDate.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.StartDate.setObjectName("StartDate")
        self.label_23 = QtWidgets.QLabel(self.AddTenantFrame_2)
        self.label_23.setGeometry(QtCore.QRect(20, 260, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: #FFFFFF;")
        self.label_23.setObjectName("label_23")
        self.ContactNum_2 = QtWidgets.QLineEdit(self.AddTenantFrame_2)
        self.ContactNum_2.setGeometry(QtCore.QRect(30, 280, 241, 20))
        self.ContactNum_2.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.ContactNum_2.setObjectName("ContactNum_2")
        self.AddRental = QtWidgets.QPushButton(self.AddTenantFrame_2)
        self.AddRental.setGeometry(QtCore.QRect(104, 380, 101, 31))
        self.AddRental.setStyleSheet("QPushButton {\n"
"    background-color: #f0f0f0; /* Solid color */\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    color: black;\n"
"    padding: 0px 0px;\n"
"    text-align: center;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    min-width: 10px;\n"
"    min-height: 4px;\n"
"    margin: 3px;\n"
"    padding-right: 0px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #94908D; /* Solid color on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #94908D; /* Solid color on pressed */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #000000; /* Solid color on disabled */\n"
"    color: #757575;\n"
"}\n"
"")
        self.AddRental.setObjectName("AddRental")
        self.UnitIDRentals = QtWidgets.QComboBox(self.AddTenantFrame_2)
        self.UnitIDRentals.setGeometry(QtCore.QRect(30, 100, 181, 22))
        self.UnitIDRentals.setStyleSheet("background-color: #FFFFFF")
        self.UnitIDRentals.setObjectName("UnitIDRentals")
        self.TenantIDRentals = QtWidgets.QComboBox(self.AddTenantFrame_2)
        self.TenantIDRentals.setGeometry(QtCore.QRect(30, 160, 181, 22))
        self.TenantIDRentals.setStyleSheet("background-color: #FFFFFF")
        self.TenantIDRentals.setObjectName("TenantIDRentals")
        self.SearchRentals = QtWidgets.QPushButton(self.RentalsPage)
        self.SearchRentals.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.SearchRentals.setFont(font)
        self.SearchRentals.setStyleSheet("QPushButton {\n"
"    background-color: #1A1A1A; /* Solid color */\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    color: #d8d8d8;\n"
"    padding: 0px 0px;\n"
"    text-align: center;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    min-width: 10px;\n"
"    min-height: 4px;\n"
"    margin: 3px;\n"
"    padding-right: 0px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #94908D; /* Solid color on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #94908D; /* Solid color on pressed */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #000000; /* Solid color on disabled */\n"
"    color: #757575;\n"
"}\n"
"")
        self.SearchRentals.setObjectName("SearchRentals")
        self.SearchBarRentals = QtWidgets.QLineEdit(self.RentalsPage)
        self.SearchBarRentals.setGeometry(QtCore.QRect(110, 10, 251, 31))
        self.SearchBarRentals.setStyleSheet("QLineEdit {\n"
"    padding: 5px; /* Padding inside the line edit */\n"
"    border: 1px solid #000000; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.SearchBarRentals.setObjectName("SearchBarRentals")
        self.SearchRentalsComboBox = QtWidgets.QComboBox(self.RentalsPage)
        self.SearchRentalsComboBox.setGeometry(QtCore.QRect(390, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setBold(True)
        font.setWeight(75)
        self.SearchRentalsComboBox.setFont(font)
        self.SearchRentalsComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #1A1A1A;  /* ComboBox background color */\n"
"    color: white;               /* ComboBox text color */\n"
"    border: none;               /* Remove default border */\n"
"    border-radius: 8px;         /* Set border radius */\n"
"    padding: 5px;               /* Add padding for better appearance */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #DDDDDD; /* Light gray for drop-down button */\n"
"    border-left-style: solid;   /* Solid border style for drop-down button */\n"
"    border-top-right-radius: 8px;  /* Match top right border radius */\n"
"    border-bottom-right-radius: 8px; /* Match bottom right border radius */\n"
"}\n"
"\n"
"\n"
"QComboBox:hover {\n"
"   background-color: #A9A9A9;  /* Change background color on hover */\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    background-color: #BDBDBD;  /* Change background color when pressed */\n"
"}")
        self.SearchRentalsComboBox.setObjectName("SearchRentalsComboBox")
        self.SearchRentalsComboBox.addItem("")
        self.SearchRentalsComboBox.addItem("")
        self.SearchRentalsComboBox.addItem("")
        self.SearchRentalsComboBox.addItem("")
        self.MainStackedWidget.addWidget(self.RentalsPage)
        self.PaymentsPage = QtWidgets.QWidget()
        self.PaymentsPage.setObjectName("PaymentsPage")
        self.PaymentsTable = QtWidgets.QTableWidget(self.PaymentsPage)
        self.PaymentsTable.setGeometry(QtCore.QRect(0, 40, 841, 481))
        self.PaymentsTable.setStyleSheet("QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #CCCCCC; \n"
"    border-radius: 10px; \n"
"     \n"
"    padding: 10px; \n"
"    margin: 20px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border-bottom: 1px solid #CCCCCC;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #C3DAF9; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A1A1A; \n"
"    color: #FFFFFF;\n"
"    border: 1px solid #CCCCCC;\n"
"    padding: 5px;\n"
"}")
        self.PaymentsTable.setObjectName("PaymentsTable")
        self.PaymentsTable.setColumnCount(5)
        self.PaymentsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.PaymentsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PaymentsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.PaymentsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.PaymentsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.PaymentsTable.setHorizontalHeaderItem(4, item)
        self.AddTenantFrame_3 = QtWidgets.QFrame(self.PaymentsPage)
        self.AddTenantFrame_3.setGeometry(QtCore.QRect(830, 60, 291, 441))
        self.AddTenantFrame_3.setStyleSheet("background-color: #1A1A1A;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"\n"
"")
        self.AddTenantFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AddTenantFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AddTenantFrame_3.setObjectName("AddTenantFrame_3")
        self.label_24 = QtWidgets.QLabel(self.AddTenantFrame_3)
        self.label_24.setGeometry(QtCore.QRect(90, 40, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: #FFFFFF;")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.AddTenantFrame_3)
        self.label_25.setGeometry(QtCore.QRect(20, 80, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color: #1A1A1A;\n"
"color: #FFFFFF;")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.AddTenantFrame_3)
        self.label_26.setGeometry(QtCore.QRect(20, 140, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color: #1A1A1A;\n"
"color: #FFFFFF;")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.AddTenantFrame_3)
        self.label_27.setGeometry(QtCore.QRect(20, 200, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: #1A1A1A;\n"
"color: #FFFFFF;")
        self.label_27.setObjectName("label_27")
        self.PaymentDate = QtWidgets.QLineEdit(self.AddTenantFrame_3)
        self.PaymentDate.setGeometry(QtCore.QRect(30, 220, 251, 20))
        self.PaymentDate.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"   \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.PaymentDate.setObjectName("PaymentDate")
        self.label_28 = QtWidgets.QLabel(self.AddTenantFrame_3)
        self.label_28.setGeometry(QtCore.QRect(20, 260, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: #1A1A1A;\n"
"color: #FFFFFF;")
        self.label_28.setObjectName("label_28")
        self.PaymentType = QtWidgets.QLineEdit(self.AddTenantFrame_3)
        self.PaymentType.setGeometry(QtCore.QRect(30, 280, 141, 20))
        self.PaymentType.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.PaymentType.setPlaceholderText("")
        self.PaymentType.setObjectName("PaymentType")
        self.AddPayment = QtWidgets.QPushButton(self.AddTenantFrame_3)
        self.AddPayment.setGeometry(QtCore.QRect(104, 380, 101, 31))
        self.AddPayment.setStyleSheet("QPushButton {\n"
"    background-color: #f0f0f0; /* Solid color */\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    color: black;\n"
"    padding: 0px 0px;\n"
"    text-align: center;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    min-width: 10px;\n"
"    min-height: 4px;\n"
"    margin: 3px;\n"
"    padding-right: 0px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #94908D; /* Solid color on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #94908D; /* Solid color on pressed */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #000000; /* Solid color on disabled */\n"
"    color: #757575;\n"
"}\n"
"")
        self.AddPayment.setObjectName("AddPayment")
        self.label_29 = QtWidgets.QLabel(self.AddTenantFrame_3)
        self.label_29.setGeometry(QtCore.QRect(20, 320, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background-color: #1A1A1A;\n"
"color: #FFFFFF;")
        self.label_29.setObjectName("label_29")
        self.PaymentStatus = QtWidgets.QLineEdit(self.AddTenantFrame_3)
        self.PaymentStatus.setGeometry(QtCore.QRect(30, 340, 113, 20))
        self.PaymentStatus.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.PaymentStatus.setObjectName("PaymentStatus")
        self.UnitIDPayments = QtWidgets.QComboBox(self.AddTenantFrame_3)
        self.UnitIDPayments.setGeometry(QtCore.QRect(30, 100, 181, 22))
        self.UnitIDPayments.setStyleSheet("background-color: #FFFFFF")
        self.UnitIDPayments.setObjectName("UnitIDPayments")
        self.TenantIDPayments = QtWidgets.QComboBox(self.AddTenantFrame_3)
        self.TenantIDPayments.setGeometry(QtCore.QRect(30, 160, 181, 22))
        self.TenantIDPayments.setStyleSheet("background-color:#FFFFFF")
        self.TenantIDPayments.setObjectName("TenantIDPayments")
        self.SearchPayments = QtWidgets.QPushButton(self.PaymentsPage)
        self.SearchPayments.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.SearchPayments.setFont(font)
        self.SearchPayments.setStyleSheet("QPushButton {\n"
"    background-color: #1A1A1A; /* Solid color */\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    color: #d8d8d8;\n"
"    padding: 0px 0px;\n"
"    text-align: center;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    min-width: 10px;\n"
"    min-height: 4px;\n"
"    margin: 3px;\n"
"    padding-right: 0px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #94908D; /* Solid color on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #94908D; /* Solid color on pressed */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #000000; /* Solid color on disabled */\n"
"    color: #757575;\n"
"}\n"
"")
        self.SearchPayments.setObjectName("SearchPayments")
        self.SearchBarPayments = QtWidgets.QLineEdit(self.PaymentsPage)
        self.SearchBarPayments.setGeometry(QtCore.QRect(110, 10, 251, 31))
        self.SearchBarPayments.setStyleSheet("QLineEdit {\n"
"    padding: 5px; /* Padding inside the line edit */\n"
"    border: 1px solid #000000; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.SearchBarPayments.setObjectName("SearchBarPayments")
        self.SearchPaymentsComboBox = QtWidgets.QComboBox(self.PaymentsPage)
        self.SearchPaymentsComboBox.setGeometry(QtCore.QRect(390, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setBold(True)
        font.setWeight(75)
        self.SearchPaymentsComboBox.setFont(font)
        self.SearchPaymentsComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #1A1A1A;  /* ComboBox background color */\n"
"    color: white;               /* ComboBox text color */\n"
"    border: none;               /* Remove default border */\n"
"    border-radius: 8px;         /* Set border radius */\n"
"    padding: 5px;               /* Add padding for better appearance */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #DDDDDD; /* Light gray for drop-down button */\n"
"    border-left-style: solid;   /* Solid border style for drop-down button */\n"
"    border-top-right-radius: 8px;  /* Match top right border radius */\n"
"    border-bottom-right-radius: 8px; /* Match bottom right border radius */\n"
"}\n"
"\n"
"\n"
"QComboBox:hover {\n"
"   background-color: #A9A9A9;  /* Change background color on hover */\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    background-color: #BDBDBD;  /* Change background color when pressed */\n"
"}")
        self.SearchPaymentsComboBox.setObjectName("SearchPaymentsComboBox")
        self.SearchPaymentsComboBox.addItem("")
        self.SearchPaymentsComboBox.addItem("")
        self.SearchPaymentsComboBox.addItem("")
        self.SearchPaymentsComboBox.addItem("")
        self.MainStackedWidget.addWidget(self.PaymentsPage)
        self.TenantsPage = QtWidgets.QWidget()
        self.TenantsPage.setObjectName("TenantsPage")
        self.TenantsTable = QtWidgets.QTableWidget(self.TenantsPage)
        self.TenantsTable.setGeometry(QtCore.QRect(0, 40, 841, 481))
        self.TenantsTable.setStyleSheet("QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #CCCCCC; \n"
"    border-radius: 10px; \n"
"   \n"
"    padding: 10px; \n"
"    margin: 20px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border-bottom: 1px solid #CCCCCC;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #C3DAF9; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A1A1A; \n"
"    color: #FFFFFF;\n"
"    border: 1px solid #CCCCCC;\n"
"    padding: 5px;\n"
"}")
        self.TenantsTable.setObjectName("TenantsTable")
        self.TenantsTable.setColumnCount(4)
        self.TenantsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TenantsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TenantsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TenantsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TenantsTable.setHorizontalHeaderItem(3, item)
        self.AddTenantFrame = QtWidgets.QFrame(self.TenantsPage)
        self.AddTenantFrame.setGeometry(QtCore.QRect(830, 60, 291, 441))
        self.AddTenantFrame.setStyleSheet("background-color: #1A1A1A;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"\n"
"\n"
"")
        self.AddTenantFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AddTenantFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AddTenantFrame.setObjectName("AddTenantFrame")
        self.label_7 = QtWidgets.QLabel(self.AddTenantFrame)
        self.label_7.setGeometry(QtCore.QRect(100, 40, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #FFFFFF;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.AddTenantFrame)
        self.label_8.setGeometry(QtCore.QRect(20, 80, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #FFFFFF;")
        self.label_8.setObjectName("label_8")
        self.TenantName = QtWidgets.QLineEdit(self.AddTenantFrame)
        self.TenantName.setGeometry(QtCore.QRect(30, 100, 241, 21))
        self.TenantName.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.TenantName.setObjectName("TenantName")
        self.TenantID = QtWidgets.QLineEdit(self.AddTenantFrame)
        self.TenantID.setGeometry(QtCore.QRect(30, 160, 151, 20))
        self.TenantID.setToolTip("")
        self.TenantID.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.TenantID.setObjectName("TenantID")
        self.label_9 = QtWidgets.QLabel(self.AddTenantFrame)
        self.label_9.setGeometry(QtCore.QRect(20, 140, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #FFFFFF;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.AddTenantFrame)
        self.label_10.setGeometry(QtCore.QRect(20, 200, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #FFFFFF;")
        self.label_10.setObjectName("label_10")
        self.EmailAdd = QtWidgets.QLineEdit(self.AddTenantFrame)
        self.EmailAdd.setGeometry(QtCore.QRect(30, 220, 251, 20))
        self.EmailAdd.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.EmailAdd.setObjectName("EmailAdd")
        self.label_11 = QtWidgets.QLabel(self.AddTenantFrame)
        self.label_11.setGeometry(QtCore.QRect(20, 260, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #FFFFFF;")
        self.label_11.setObjectName("label_11")
        self.ContactNum = QtWidgets.QLineEdit(self.AddTenantFrame)
        self.ContactNum.setGeometry(QtCore.QRect(60, 290, 221, 21))
        self.ContactNum.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"   \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.ContactNum.setObjectName("ContactNum")
        self.label_12 = QtWidgets.QLabel(self.AddTenantFrame)
        self.label_12.setGeometry(QtCore.QRect(30, 290, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: #FFFFFF;")
        self.label_12.setObjectName("label_12")
        self.AddTenant = QtWidgets.QPushButton(self.AddTenantFrame)
        self.AddTenant.setGeometry(QtCore.QRect(100, 350, 91, 31))
        self.AddTenant.setStyleSheet("QPushButton {\n"
"    background-color: #f0f0f0; /* Solid color */\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    color: black;\n"
"    padding: 0px 0px;\n"
"    text-align: center;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    min-width: 10px;\n"
"    min-height: 4px;\n"
"    margin: 3px;\n"
"    padding-right: 0px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #94908D; /* Solid color on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #94908D; /* Solid color on pressed */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #000000; /* Solid color on disabled */\n"
"    color: #757575;\n"
"}\n"
"")
        self.AddTenant.setObjectName("AddTenant")
        self.SearchTenant = QtWidgets.QPushButton(self.TenantsPage)
        self.SearchTenant.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.SearchTenant.setFont(font)
        self.SearchTenant.setStyleSheet("QPushButton {\n"
"    background-color: #1A1A1A; /* Solid color */\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    color: #d8d8d8;\n"
"    padding: 0px 0px;\n"
"    text-align: center;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    min-width: 10px;\n"
"    min-height: 4px;\n"
"    margin: 3px;\n"
"    padding-right: 0px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #94908D; /* Solid color on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #94908D; /* Solid color on pressed */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #000000; /* Solid color on disabled */\n"
"    color: #757575;\n"
"}\n"
"")
        self.SearchTenant.setObjectName("SearchTenant")
        self.SearchBarTenants = QtWidgets.QLineEdit(self.TenantsPage)
        self.SearchBarTenants.setGeometry(QtCore.QRect(110, 10, 251, 31))
        self.SearchBarTenants.setStyleSheet("QLineEdit {\n"
"    padding: 5px; /* Padding inside the line edit */\n"
"    border: 1px solid #000000; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"   \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.SearchBarTenants.setObjectName("SearchBarTenants")
        self.SearchTenantComboBox = QtWidgets.QComboBox(self.TenantsPage)
        self.SearchTenantComboBox.setGeometry(QtCore.QRect(390, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setBold(True)
        font.setWeight(75)
        self.SearchTenantComboBox.setFont(font)
        self.SearchTenantComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #1A1A1A;;  /* ComboBox background color */\n"
"    color: white;               /* ComboBox text color */\n"
"    border: none;               /* Remove default border */\n"
"    border-radius: 8px;         /* Set border radius */\n"
"    padding: 5px;               /* Add padding for better appearance */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #DDDDDD; /* Light gray for drop-down button */\n"
"    border-left-style: solid;   /* Solid border style for drop-down button */\n"
"    border-top-right-radius: 8px;  /* Match top right border radius */\n"
"    border-bottom-right-radius: 8px; /* Match bottom right border radius */\n"
"}\n"
"\n"
"\n"
"QComboBox:hover {\n"
"   background-color: #A9A9A9;  /* Change background color on hover */\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    background-color: #BDBDBD;  /* Change background color when pressed */\n"
"}")
        self.SearchTenantComboBox.setObjectName("SearchTenantComboBox")
        self.SearchTenantComboBox.addItem("")
        self.SearchTenantComboBox.addItem("")
        self.frame_2 = QtWidgets.QFrame(self.TenantsPage)
        self.frame_2.setGeometry(QtCore.QRect(640, 10, 181, 32))
        self.frame_2.setStyleSheet("border: 2px solid;\n"
"border-radius: 8px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 7, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(" border: none;\n"
"border-radius: 3px;")
        self.label_3.setObjectName("label_3")
        self.TotalTenants = QtWidgets.QLabel(self.frame_2)
        self.TotalTenants.setGeometry(QtCore.QRect(140, 7, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TotalTenants.setFont(font)
        self.TotalTenants.setStyleSheet(" border: none")
        self.TotalTenants.setObjectName("TotalTenants")
        self.MainStackedWidget.addWidget(self.TenantsPage)
        self.UnitsPage = QtWidgets.QWidget()
        self.UnitsPage.setObjectName("UnitsPage")
        self.UnitsTable = QtWidgets.QTableWidget(self.UnitsPage)
        self.UnitsTable.setGeometry(QtCore.QRect(0, 40, 841, 481))
        self.UnitsTable.setStyleSheet("QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #CCCCCC; \n"
"    border-radius: 10px; \n"
"     \n"
"    padding: 10px; \n"
"    margin: 20px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border-bottom: 1px solid #CCCCCC;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #C3DAF9; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #1A1A1A; \n"
"    color: #FFFFFF;\n"
"    border: 1px solid #CCCCCC;\n"
"    padding: 5px;\n"
"}")
        self.UnitsTable.setObjectName("UnitsTable")
        self.UnitsTable.setColumnCount(5)
        self.UnitsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.UnitsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.UnitsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.UnitsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.UnitsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.UnitsTable.setHorizontalHeaderItem(4, item)
        self.AddUnitFrame = QtWidgets.QFrame(self.UnitsPage)
        self.AddUnitFrame.setGeometry(QtCore.QRect(830, 60, 291, 441))
        self.AddUnitFrame.setStyleSheet("background-color: #1A1A1A;\n"
"border-top-right-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;")
        self.AddUnitFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AddUnitFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AddUnitFrame.setObjectName("AddUnitFrame")
        self.label_13 = QtWidgets.QLabel(self.AddUnitFrame)
        self.label_13.setGeometry(QtCore.QRect(110, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: #FFFFFF;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.AddUnitFrame)
        self.label_14.setGeometry(QtCore.QRect(20, 80, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: #FFFFFF;")
        self.label_14.setObjectName("label_14")
        self.UnitName = QtWidgets.QLineEdit(self.AddUnitFrame)
        self.UnitName.setGeometry(QtCore.QRect(30, 100, 241, 21))
        self.UnitName.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.UnitName.setObjectName("UnitName")
        self.UnitID = QtWidgets.QLineEdit(self.AddUnitFrame)
        self.UnitID.setGeometry(QtCore.QRect(30, 160, 151, 20))
        self.UnitID.setToolTip("")
        self.UnitID.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.UnitID.setObjectName("UnitID")
        self.label_15 = QtWidgets.QLabel(self.AddUnitFrame)
        self.label_15.setGeometry(QtCore.QRect(20, 140, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: #FFFFFF;")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.AddUnitFrame)
        self.label_16.setGeometry(QtCore.QRect(20, 200, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: #FFFFFF;")
        self.label_16.setObjectName("label_16")
        self.StoreType = QtWidgets.QLineEdit(self.AddUnitFrame)
        self.StoreType.setGeometry(QtCore.QRect(30, 220, 251, 20))
        self.StoreType.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.StoreType.setObjectName("StoreType")
        self.label_17 = QtWidgets.QLabel(self.AddUnitFrame)
        self.label_17.setGeometry(QtCore.QRect(20, 260, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: #FFFFFF;")
        self.label_17.setObjectName("label_17")
        self.UnitPrice = QtWidgets.QLineEdit(self.AddUnitFrame)
        self.UnitPrice.setGeometry(QtCore.QRect(40, 290, 191, 20))
        self.UnitPrice.setStyleSheet("QLineEdit {\n"
"    padding: 2px; /* Padding inside the line edit */\n"
"    border: 1px solid #CCCCCC; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"   \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.UnitPrice.setPlaceholderText("")
        self.UnitPrice.setObjectName("UnitPrice")
        self.label_18 = QtWidgets.QLabel(self.AddUnitFrame)
        self.label_18.setGeometry(QtCore.QRect(20, 290, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #FFFFFF;")
        self.label_18.setObjectName("label_18")
        self.AddUnit = QtWidgets.QPushButton(self.AddUnitFrame)
        self.AddUnit.setGeometry(QtCore.QRect(100, 350, 91, 31))
        self.AddUnit.setStyleSheet("QPushButton {\n"
"    background-color: #f0f0f0; /* Solid color */\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    color: black;\n"
"    padding: 0px 0px;\n"
"    text-align: center;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    min-width: 10px;\n"
"    min-height: 4px;\n"
"    margin: 3px;\n"
"    padding-right: 0px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #94908D; /* Solid color on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #94908D; /* Solid color on pressed */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #000000; /* Solid color on disabled */\n"
"    color: #757575;\n"
"}\n"
"")
        self.AddUnit.setObjectName("AddUnit")
        self.SearchUnit = QtWidgets.QPushButton(self.UnitsPage)
        self.SearchUnit.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.SearchUnit.setFont(font)
        self.SearchUnit.setStyleSheet("QPushButton {\n"
"    background-color: #1A1A1A; /* Solid color */\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    color: #d8d8d8;\n"
"    padding: 0px 0px;\n"
"    text-align: center;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    min-width: 10px;\n"
"    min-height: 4px;\n"
"    margin: 3px;\n"
"    padding-right: 0px;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #94908D; /* Solid color on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #94908D; /* Solid color on pressed */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #000000; /* Solid color on disabled */\n"
"    color: #757575;\n"
"}\n"
"")
        self.SearchUnit.setObjectName("SearchUnit")
        self.SearchBarUnit = QtWidgets.QLineEdit(self.UnitsPage)
        self.SearchBarUnit.setGeometry(QtCore.QRect(110, 10, 251, 31))
        self.SearchBarUnit.setStyleSheet("QLineEdit {\n"
"    padding: 5px; /* Padding inside the line edit */\n"
"    border: 1px solid #000000; /* Border with light gray color */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Font size */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #AAAAAA; /* Darker border color on hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50; /* Green border color when focused */\n"
"    /* Optional: Outline or box-shadow to indicate focus */\n"
"    outline: none;\n"
"   \n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #F0F0F0; /* Light gray background when disabled */\n"
"    color: #808080; /* Dimmed text color when disabled */\n"
"    border-color: #D3D3D3; /* Light gray border color when disabled */\n"
"}")
        self.SearchBarUnit.setObjectName("SearchBarUnit")
        self.SearchUnitComboBox = QtWidgets.QComboBox(self.UnitsPage)
        self.SearchUnitComboBox.setGeometry(QtCore.QRect(390, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setBold(True)
        font.setWeight(75)
        self.SearchUnitComboBox.setFont(font)
        self.SearchUnitComboBox.setStyleSheet("QComboBox {\n"
"    background-color: #1A1A1A;;  /* ComboBox background color */\n"
"    color: white;               /* ComboBox text color */\n"
"    border: none;               /* Remove default border */\n"
"    border-radius: 8px;         /* Set border radius */\n"
"    padding: 5px;               /* Add padding for better appearance */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: #DDDDDD; /* Light gray for drop-down button */\n"
"    border-left-style: solid;   /* Solid border style for drop-down button */\n"
"    border-top-right-radius: 8px;  /* Match top right border radius */\n"
"    border-bottom-right-radius: 8px; /* Match bottom right border radius */\n"
"}\n"
"\n"
"\n"
"QComboBox:hover {\n"
"   background-color: #A9A9A9;  /* Change background color on hover */\n"
"}\n"
"\n"
"QComboBox:pressed {\n"
"    background-color: #BDBDBD;  /* Change background color when pressed */\n"
"}")
        self.SearchUnitComboBox.setObjectName("SearchUnitComboBox")
        self.SearchUnitComboBox.addItem("")
        self.SearchUnitComboBox.addItem("")
        self.frame = QtWidgets.QFrame(self.UnitsPage)
        self.frame.setGeometry(QtCore.QRect(550, 10, 181, 32))
        self.frame.setStyleSheet("border: 2px solid;\n"
"border-radius: 8px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.TotalUnits = QtWidgets.QLabel(self.frame)
        self.TotalUnits.setGeometry(QtCore.QRect(130, 7, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TotalUnits.setFont(font)
        self.TotalUnits.setStyleSheet(" border: none")
        self.TotalUnits.setObjectName("TotalUnits")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 7, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(" border: none;\n"
"border-radius: 3px;")
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.UnitsPage)
        self.frame_3.setGeometry(QtCore.QRect(750, 10, 181, 32))
        self.frame_3.setStyleSheet("border: 2px solid;\n"
"border-radius: 8px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 7, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(" border: none;\n"
"border-radius: 3px;")
        self.label_4.setObjectName("label_4")
        self.AvailableUnits = QtWidgets.QLabel(self.frame_3)
        self.AvailableUnits.setGeometry(QtCore.QRect(140, 7, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AvailableUnits.setFont(font)
        self.AvailableUnits.setStyleSheet(" border: none;\n"
"border-radius: 3px;")
        self.AvailableUnits.setObjectName("AvailableUnits")
        self.MainStackedWidget.addWidget(self.UnitsPage)
        self.DashBoardFrame = QtWidgets.QFrame(self.MainWidget)
        self.DashBoardFrame.setGeometry(QtCore.QRect(0, 0, 1131, 81))
        self.DashBoardFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DashBoardFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DashBoardFrame.setObjectName("DashBoardFrame")
        self.DashBoardHolderFrame = QtWidgets.QFrame(self.DashBoardFrame)
        self.DashBoardHolderFrame.setGeometry(QtCore.QRect(0, 20, 1131, 41))
        self.DashBoardHolderFrame.setStyleSheet("background-color: #1A1A1A")
        self.DashBoardHolderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DashBoardHolderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DashBoardHolderFrame.setObjectName("DashBoardHolderFrame")
        self.DashboardButton = QtWidgets.QPushButton(self.DashBoardHolderFrame)
        self.DashboardButton.setGeometry(QtCore.QRect(30, 10, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DashboardButton.setFont(font)
        self.DashboardButton.setStyleSheet("QPushButton {\n"
"        background-color: #FFFFFF;  \n"
"        color: black;               \n"
"        border: none;               \n"
"        border-radius: 5px;         \n"
"         }")
        self.DashboardButton.setObjectName("DashboardButton")
        self.TenantsButton = QtWidgets.QPushButton(self.DashBoardHolderFrame)
        self.TenantsButton.setGeometry(QtCore.QRect(180, 10, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setBold(True)
        font.setWeight(75)
        self.TenantsButton.setFont(font)
        self.TenantsButton.setStyleSheet("QPushButton {\n"
"        background-color: #FFFFFF;  \n"
"        color: black;               \n"
"        border: none;               \n"
"        border-radius: 8px;         \n"
"                 \n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #E0E0E0;  \n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #BDBDBD;  \n"
"    }")
        self.TenantsButton.setObjectName("TenantsButton")
        self.UnitsButton = QtWidgets.QPushButton(self.DashBoardHolderFrame)
        self.UnitsButton.setGeometry(QtCore.QRect(270, 10, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.UnitsButton.setFont(font)
        self.UnitsButton.setStyleSheet("QPushButton {\n"
"        background-color: #FFFFFF;  \n"
"        color: black;               \n"
"        border: none;               \n"
"        border-radius: 8px;         \n"
"                 \n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #E0E0E0;  \n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #BDBDBD;  \n"
"    }")
        self.UnitsButton.setObjectName("UnitsButton")
        self.RentalsButton = QtWidgets.QPushButton(self.DashBoardHolderFrame)
        self.RentalsButton.setGeometry(QtCore.QRect(360, 10, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setBold(True)
        font.setWeight(75)
        self.RentalsButton.setFont(font)
        self.RentalsButton.setStyleSheet("QPushButton {\n"
"        background-color: #FFFFFF;  \n"
"        color: black;               \n"
"        border: none;               \n"
"        border-radius: 8px;         \n"
"                 \n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #E0E0E0;  \n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #BDBDBD;  \n"
"    }")
        self.RentalsButton.setObjectName("RentalsButton")
        self.PaymentsButton = QtWidgets.QPushButton(self.DashBoardHolderFrame)
        self.PaymentsButton.setGeometry(QtCore.QRect(450, 10, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setBold(True)
        font.setWeight(75)
        self.PaymentsButton.setFont(font)
        self.PaymentsButton.setStyleSheet("QPushButton {\n"
"        background-color: #FFFFFF;  \n"
"        color: black;               \n"
"        border: none;               \n"
"        border-radius: 8px;         \n"
"                 \n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #E0E0E0;  \n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #BDBDBD;  \n"
"    }")
        self.PaymentsButton.setObjectName("PaymentsButton")
        self.label = QtWidgets.QLabel(self.DashBoardHolderFrame)
        self.label.setGeometry(QtCore.QRect(880, 10, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FFFFFF")
        self.label.setObjectName("label")
        self.LoginStackedWidget.addWidget(self.MainWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.TenantsTable.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)    #Modified
        self.TenantsTable.horizontalHeader().setStretchLastSection(True)                                     #Modified 

        self.UnitsTable.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)      #Modified
        self.UnitsTable.horizontalHeader().setStretchLastSection(True)                                       #Modified

        self.PaymentsTable.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)    #Modified
        self.PaymentsTable.horizontalHeader().setStretchLastSection(True)                                     #Modified 

        self.RentalsTable.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)    #Modified
        self.RentalsTable.horizontalHeader().setStretchLastSection(True)

        self.retranslateUi(MainWindow)
        self.LoginStackedWidget.setCurrentIndex(1)
        self.MainStackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "TOTAL EARNINGS"))
        self.label_6.setText(_translate("MainWindow", "₱"))
        self.TotalEarnings.setText(_translate("MainWindow", "50,000"))
        item = self.RentalsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "UnitID"))
        item = self.RentalsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TenantID"))
        item = self.RentalsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "StartDate"))
        item = self.RentalsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "EndDate"))
        self.label_19.setText(_translate("MainWindow", "ADD RENTALS"))
        self.label_20.setText(_translate("MainWindow", "Unit ID:"))
        self.label_21.setText(_translate("MainWindow", "Tenant ID:"))
        self.label_22.setText(_translate("MainWindow", "Start Date:"))
        self.StartDate.setPlaceholderText(_translate("MainWindow", "YYYY-MM-DD"))
        self.label_23.setText(_translate("MainWindow", "End Date:"))
        self.ContactNum_2.setPlaceholderText(_translate("MainWindow", "YYYY-MM-DD"))
        self.AddRental.setText(_translate("MainWindow", "Add"))
        self.SearchRentals.setText(_translate("MainWindow", "Search"))
        self.SearchRentalsComboBox.setItemText(0, _translate("MainWindow", "Tenant Name"))
        self.SearchRentalsComboBox.setItemText(1, _translate("MainWindow", "Unit Name"))
        self.SearchRentalsComboBox.setItemText(2, _translate("MainWindow", "Unit ID"))
        self.SearchRentalsComboBox.setItemText(3, _translate("MainWindow", "Tenant ID"))
        item = self.PaymentsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "UnitID"))
        item = self.PaymentsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TenantID"))
        item = self.PaymentsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PaymentDate"))
        item = self.PaymentsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PaymentType"))
        item = self.PaymentsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PaymentStatus"))
        self.label_24.setText(_translate("MainWindow", "ADD PAYMENT"))
        self.label_25.setText(_translate("MainWindow", "Unit ID:"))
        self.label_26.setText(_translate("MainWindow", "Tenant ID:"))
        self.label_27.setText(_translate("MainWindow", "Payment Date:"))
        self.PaymentDate.setPlaceholderText(_translate("MainWindow", "YYYY-MM-DD"))
        self.label_28.setText(_translate("MainWindow", "Payment Type:"))
        self.AddPayment.setText(_translate("MainWindow", "Add"))
        self.label_29.setText(_translate("MainWindow", "Payment Status:"))
        self.SearchPayments.setText(_translate("MainWindow", "Search"))
        self.SearchPaymentsComboBox.setItemText(0, _translate("MainWindow", "Tenant Name"))
        self.SearchPaymentsComboBox.setItemText(1, _translate("MainWindow", "Unit Name"))
        self.SearchPaymentsComboBox.setItemText(2, _translate("MainWindow", "Unit ID"))
        self.SearchPaymentsComboBox.setItemText(3, _translate("MainWindow", "Tenant ID"))
        item = self.TenantsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TenantID"))
        item = self.TenantsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TenantName"))
        item = self.TenantsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "EmailAddress"))
        item = self.TenantsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ContactNumber"))
        self.label_7.setText(_translate("MainWindow", "ADD TENANT"))
        self.label_8.setText(_translate("MainWindow", "Tenant Name:"))
        self.TenantID.setPlaceholderText(_translate("MainWindow", "XXXX-XXXX"))
        self.label_9.setText(_translate("MainWindow", "Tenant ID:"))
        self.label_10.setText(_translate("MainWindow", "Email Address:"))
        self.label_11.setText(_translate("MainWindow", "Contact Number:"))
        self.ContactNum.setPlaceholderText(_translate("MainWindow", "000 0000 000"))
        self.label_12.setText(_translate("MainWindow", "+63"))
        self.AddTenant.setText(_translate("MainWindow", "Add"))
        self.SearchTenant.setText(_translate("MainWindow", "Search"))
        self.SearchTenantComboBox.setItemText(0, _translate("MainWindow", "Tenant Name"))
        self.SearchTenantComboBox.setItemText(1, _translate("MainWindow", "Tenant ID"))
        self.label_3.setText(_translate("MainWindow", "TOTAL TENANTS"))
        self.TotalTenants.setText(_translate("MainWindow", "24"))
        item = self.UnitsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "UnitID"))
        item = self.UnitsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UnitName"))
        item = self.UnitsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "StoreType"))
        item = self.UnitsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "UnitStatus"))
        item = self.UnitsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "UnitPrice"))
        self.label_13.setText(_translate("MainWindow", "ADD UNIT"))
        self.label_14.setText(_translate("MainWindow", "Unit Name:"))
        self.UnitID.setPlaceholderText(_translate("MainWindow", "AAA-XXXX"))
        self.label_15.setText(_translate("MainWindow", "Unit ID:"))
        self.label_16.setText(_translate("MainWindow", "Store Type:"))
        self.label_17.setText(_translate("MainWindow", "Unit Price:"))
        self.label_18.setText(_translate("MainWindow", "₱"))
        self.AddUnit.setText(_translate("MainWindow", "Add"))
        self.SearchUnit.setText(_translate("MainWindow", "Search"))
        self.SearchUnitComboBox.setItemText(0, _translate("MainWindow", "Unit Name"))
        self.SearchUnitComboBox.setItemText(1, _translate("MainWindow", "Unit ID"))
        self.TotalUnits.setText(_translate("MainWindow", "76"))
        self.label_2.setText(_translate("MainWindow", "TOTAL UNITS"))
        self.label_4.setText(_translate("MainWindow", "AVAILABLE UNITS"))
        self.AvailableUnits.setText(_translate("MainWindow", "23"))
        self.DashboardButton.setText(_translate("MainWindow", "MENU"))
        self.TenantsButton.setText(_translate("MainWindow", "TENANTS"))
        self.UnitsButton.setText(_translate("MainWindow", "UNITS"))
        self.RentalsButton.setText(_translate("MainWindow", "RENTALS"))
        self.PaymentsButton.setText(_translate("MainWindow", "PAYMENTS"))
        self.label.setText(_translate("MainWindow", "STORE RENTAL MANAGEMENT SYSTEM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
